"""Add cover_image and description to park

Revision ID: 643772972892
Revises: dcf0a4138729
Create Date: 2025-12-17 17:07:52.893557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643772972892'
down_revision: Union[str, Sequence[str], None] = 'dcf0a4138729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parks', sa.Column('cover_image', sa.String(), nullable=True))
    op.add_column('parks', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('visited_parks', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('visited_parks', 'park_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visited_parks', 'park_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('visited_parks', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('parks', 'description')
    op.drop_column('parks', 'cover_image')
    # ### end Alembic commands ###
